import { JetBrains_Mono } from 'next/font/google';
import { Inter } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ['latin'],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ['latin'],
});

export const metadata = {
  title: "Victor Iliya | DevOps Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} ${inter.variable}` }>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
